# Generated by Django 4.1.6 on 2023-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createNews',
            fields=[
                ('newsId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('newsDetails', models.TextField()),
                ('coverImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
